# Generated by Django 5.2.3 on 2025-06-12 14:28

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='категория статьи')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорию',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('заметка', 'заметка'), ('статья', 'статья'), ('новое в праве', 'новое в праве')], db_index=True, verbose_name='тип статьи')),
                ('content', models.TextField(max_length=3000, verbose_name='текст статьи')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение для статьи')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='сategory', related_query_name='сategory', to='articles.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статью',
            },
        ),
    ]
