# Generated by Django 5.2.3 on 2025-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(db_index=True, max_length=3000, verbose_name='текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата изменения'),
        ),
    ]
