services:

  web:
    build: backend/lawyer_web
    command: gunicorn --config gunicorn.conf.py lawyer_web.wsgi:application
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONPATH=/app
    volumes:
      - static_volume:/app/static

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/lawyer_web/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - web

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: backend/lawyer_web
    command: celery -A lawyer_web worker --loglevel=info
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend/lawyer_web:/app/
    healthcheck:
      test: [ "CMD", "celery", "-A", "lawyer_web", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/my-app:/app  # Монтирует исходный код
      - /app/node_modules     # Сохраняет node_modules отдельно
    environment:
      - NODE_ENV=development
    depends_on:
      - web

volumes:
  static_volume: