services:

  web:
    build: .
    command: gunicorn --config gunicorn.conf.py lawyer_web.wsgi:application
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONPATH=/app
    volumes:
      - static_volume:/app/static

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - web

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A lawyer_web worker --loglevel=info
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app/
    healthcheck:
      test: [ "CMD", "celery", "-A", "lawyer_web", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  static_volume: