services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A lawyer_web worker --loglevel=info
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app/
    healthcheck:
      test: [ "CMD", "celery", "-A", "lawyer_web", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  static_volume: