# Generated by Django 5.2.3 on 2025-06-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50, verbose_name='Наименование практики')),
                ('description', models.TextField(max_length=300, verbose_name='Описание практики')),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_case', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание процесса')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='начало процесса')),
                ('end_date', models.DateTimeField(verbose_name='окончание процесса')),
                ('review', models.CharField(max_length=200, verbose_name='отзыв')),
                ('case_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice', related_query_name='practice', to='cases.practice', verbose_name='категория процесса')),
            ],
        ),
    ]
