# Generated by Django 5.2.3 on 2025-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'verbose_name': 'Делопроизводство', 'verbose_name_plural': 'Делопроизводство'},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'verbose_name': 'Практику', 'verbose_name_plural': 'Практика'},
        ),
        migrations.AlterField(
            model_name='cases',
            name='review',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='отзыв'),
        ),
    ]
