# Generated by Django 5.2.3 on 2025-06-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_cases_options_alter_practice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='case_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice', related_query_name='practice', to='cases.practice', verbose_name='категория процесса'),
        ),
    ]
