# Generated by Django 5.2.3 on 2025-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_cases_case_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='окончание процесса'),
        ),
    ]
