# Generated by Django 5.2.3 on 2025-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_cases_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='description',
            field=models.TextField(db_index=True, max_length=3000, verbose_name='Описание процесса'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='end_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='окончание процесса'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='начало процесса'),
        ),
    ]
