# Generated by Django 5.2.3 on 2025-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_networks',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='биография'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='фейсбук'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='инстаграм'),
        ),
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='сайт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='телеграмм'),
        ),
        migrations.AddField(
            model_name='profile',
            name='viber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='вайбер'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ватсап'),
        ),
        migrations.AddField(
            model_name='profile',
            name='x',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='твиттер'),
        ),
    ]
