# Generated by Django 5.2.3 on 2025-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_instagram_profile_inst_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('house', models.CharField(max_length=20)),
                ('structure', models.CharField(blank=True, max_length=100)),
                ('housing', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('coordinates_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адрес',
            },
        ),
    ]
