# Generated by Django 5.2.3 on 2025-09-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_max',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAX'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вконтакте'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=20, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='address',
            name='housing',
            field=models.CharField(blank=True, max_length=100, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='address',
            name='structure',
            field=models.CharField(blank=True, max_length=100, verbose_name='Строение'),
        ),
    ]
