name: Lawyer_web check

on:
  push:
    branches:
      - dev_back

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12


      - name: Install dependencies
        run: |
          cd backend/lawyer_web
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend/lawyer_web
          python manage.py test